
/**
 * @file    i2c_helper.h
 * @brief   I2C helper functions for ESP8266 peripheral communication utilities and drivers like SSD1306, sensors, etc.
 * @author  Umesh Puri
 * @date    2025-06-02
 * @version 1.0
 *
 * This file provides utility functions for initializing and communicating
 * with devices over the I2C bus, used by peripherals such as SSD1306 displays,
 * sensors, and communication modules on STM32F103.
 *
 * @license MIT License
 * Copyright (c) 2025 Umesh
 */

#ifndef _I2C_HELPER_
#define _I2C_HELPER_


#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#define I2C_MASTER_SCL_IO 16         /*!< gpio number for I2C master clock */
#define I2C_MASTER_SDA_IO 17         /*!< gpio number for I2C master data  */
#define I2C_MASTER_NUM I2C_NUM_0    /*!< I2C port number for master dev */
#define I2C_MASTER_TX_BUF_DISABLE 0 /*!< I2C master do not need buffer */
#define I2C_MASTER_RX_BUF_DISABLE 0 /*!< I2C master do not need buffer */

#define WRITE_BIT I2C_MASTER_WRITE /*!< I2C master write */
#define READ_BIT I2C_MASTER_READ   /*!< I2C master read */
#define I2C_MASTER_FREQ_HZ 100000 /*CLOCK*/
#define OLED_I2C_ADDRESS 0x3C

void i2c_init(void);

void i2c_write(uint8_t data);

#endif